package Proyecto;
//esta es la final para el zip

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

public class Main extends javax.swing.JFrame {
    pnlSeparar pnlseparar  = new pnlSeparar(this);
    pnlSimbolos pnlsimbolos;
    pnlEstados pnlestados = new pnlEstados();
    String nombreArchivo;
    String rutaArchivo;
    String archivo;
    int paginasA;
    int paginaA;
    int tamA;
    byte imprimir=15;
    boolean seAbrioCorrecto=false;
    /**
     * Creates new form Paneles
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        txtArchivo.setEditable(false);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlControles = new javax.swing.JPanel();
        btnSeparar = new javax.swing.JButton();
        btnSimbolos = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        pnlAnalisis = new javax.swing.JPanel();
        pnlArchivo = new javax.swing.JPanel();
        btnAtrasArchivo = new javax.swing.JButton();
        btnSiguienteArchivo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArchivo = new javax.swing.JTextArea();
        lblPaginaA = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnArchivo = new javax.swing.JMenu();
        smnCargarArchivo = new javax.swing.JMenuItem();
        smnSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlControles.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24))); // NOI18N

        btnSeparar.setBackground(new java.awt.Color(255, 153, 51));
        btnSeparar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSeparar.setText("Separar");
        btnSeparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSepararActionPerformed(evt);
            }
        });

        btnSimbolos.setBackground(new java.awt.Color(255, 153, 51));
        btnSimbolos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSimbolos.setText("Simbolos");
        btnSimbolos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimbolosActionPerformed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(255, 153, 51));
        exit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        exit.setText("Salir");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlControlesLayout = new javax.swing.GroupLayout(pnlControles);
        pnlControles.setLayout(pnlControlesLayout);
        pnlControlesLayout.setHorizontalGroup(
            pnlControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSeparar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlControlesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSimbolos))
                    .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlControlesLayout.setVerticalGroup(
            pnlControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSeparar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSimbolos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exit)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pnlAnalisis.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 24))); // NOI18N
        pnlAnalisis.setLayout(new java.awt.BorderLayout());

        pnlArchivo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Archivo ASM", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24))); // NOI18N

        btnAtrasArchivo.setBackground(new java.awt.Color(255, 255, 153));
        btnAtrasArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/atras.png"))); // NOI18N
        btnAtrasArchivo.setMaximumSize(new java.awt.Dimension(545, 521));
        btnAtrasArchivo.setMinimumSize(new java.awt.Dimension(545, 521));
        btnAtrasArchivo.setPreferredSize(new java.awt.Dimension(545, 521));
        btnAtrasArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasArchivoActionPerformed(evt);
            }
        });

        btnSiguienteArchivo.setBackground(new java.awt.Color(255, 255, 153));
        btnSiguienteArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/siguiente.png"))); // NOI18N
        btnSiguienteArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteArchivoActionPerformed(evt);
            }
        });

        txtArchivo.setColumns(20);
        txtArchivo.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 14)); // NOI18N
        txtArchivo.setRows(5);
        jScrollPane1.setViewportView(txtArchivo);

        javax.swing.GroupLayout pnlArchivoLayout = new javax.swing.GroupLayout(pnlArchivo);
        pnlArchivo.setLayout(pnlArchivoLayout);
        pnlArchivoLayout.setHorizontalGroup(
            pnlArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArchivoLayout.createSequentialGroup()
                .addGroup(pnlArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlArchivoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(lblPaginaA, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlArchivoLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnAtrasArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119)
                        .addComponent(btnSiguienteArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlArchivoLayout.setVerticalGroup(
            pnlArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnlArchivoLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(pnlArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPaginaA, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlArchivoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSiguienteArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAtrasArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 51, 204));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 0)));
        jMenuBar1.setForeground(new java.awt.Color(153, 153, 0));

        mnArchivo.setBackground(new java.awt.Color(255, 102, 51));
        mnArchivo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mnArchivo.setText("Archivo");

        smnCargarArchivo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        smnCargarArchivo.setText("Seleccione archivo");
        smnCargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnCargarArchivoActionPerformed(evt);
            }
        });
        mnArchivo.add(smnCargarArchivo);

        smnSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        smnSalir.setText("Salir");
        smnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnSalirActionPerformed(evt);
            }
        });
        mnArchivo.add(smnSalir);

        jMenuBar1.add(mnArchivo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(pnlArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlControles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAnalisis, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAnalisis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlControles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pnlControles.getAccessibleContext().setAccessibleName("Controles1");
        pnlArchivo.getAccessibleContext().setAccessibleName("Archivo ASS\n\n");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSepararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSepararActionPerformed
        if (seAbrioCorrecto) {
            pnlseparar.palabrasReservadas();
            pnlseparar.separarElementos();
            pnlAnalisis.setBorder(javax.swing.BorderFactory.createTitledBorder("Separacion de elementos"));
            pnlAnalisis.removeAll();
            pnlAnalisis.add(pnlseparar);
            pnlAnalisis.validate();
            pnlAnalisis.repaint();
        }

    }//GEN-LAST:event_btnSepararActionPerformed

    private void btnAtrasArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasArchivoActionPerformed
        if(paginaA>1){
            paginaA--;
            mostrarArchivo();
            //lblPaginaA.setText("Pagina: "+paginaA+" de "+paginasA);
        }
    }//GEN-LAST:event_btnAtrasArchivoActionPerformed

    private void btnSiguienteArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteArchivoActionPerformed
        if(paginaA<paginasA){
            paginaA++;
            mostrarArchivo();
            //lblPaginaA.setText("Pagina: "+paginaA+" de "+paginasA);
        }
    }//GEN-LAST:event_btnSiguienteArchivoActionPerformed

    private void smnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_smnSalirActionPerformed

    private void smnCargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnCargarArchivoActionPerformed
        JFileChooser selecc = new JFileChooser();
        FileNameExtensionFilter filterArch = new FileNameExtensionFilter("ASM", "asm");
        selecc.setFileFilter(filterArch);
        int option = selecc.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            File fichero = selecc.getSelectedFile();
            if (fichero.getName().endsWith(".asm")) {
                nombreArchivo = selecc.getSelectedFile().getName();
                rutaArchivo = selecc.getSelectedFile().toString();
                try (FileReader fr = new FileReader(fichero)) {
                    archivo = "";
                    int valor = fr.read();
                    while (valor != -1) {
                        archivo = archivo + (char) valor;
                        valor = fr.read();
                    }
                    //txtArea.setText(archivo);
                    construirArchivo();
                } catch (IOException e1) {
                    JOptionPane.showMessageDialog(null,"Error al abrir el archivo 1");
                }
            }else {
                JOptionPane.showMessageDialog(null,"Error el archivo es inválido ");
            }
        }
    }//GEN-LAST:event_smnCargarArchivoActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void btnSimbolosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimbolosActionPerformed
        // TODO add your handling code here:
        if (seAbrioCorrecto) {
            pnlAnalisis.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabla de Simbolos"));
            pnlAnalisis.removeAll();
            pnlAnalisis.add(pnlsimbolos);
            pnlAnalisis.validate();
            pnlAnalisis.repaint();
        }
    }//GEN-LAST:event_btnSimbolosActionPerformed
    public void construirArchivo() throws FileNotFoundException{
        int cont=1;
        paginasA=1;
        tamA=archivo.length();
        for (int i = 0; i < tamA; i++) {
            if (archivo.charAt(i) == '\n') {
                if (cont == imprimir) {
                    paginasA++;
                    cont=1;
                }else{
                    cont++;
                }
            }
        }
        paginaA=1;
        mostrarArchivo();
        //lblPaginaA.setText("Pagina: "+paginaA+" de "+paginasA);
        pnlseparar.archivo=archivo;
        pnlsimbolos = new pnlSimbolos(nombreArchivo,rutaArchivo,this);
        seAbrioCorrecto=true;
    }
    public void mostrarArchivo(){
        int cont=1;
        int renglonObjetivo=paginaA;
        int renglonBuscador=1;
        String pag="";
        int i=0;
        while(renglonBuscador<renglonObjetivo){
            if (archivo.charAt(i) == '\n') {
                if(cont==imprimir){
                    renglonBuscador++;
                    cont=1;
                }else{
                    cont++;
                }
            }
            i++;
        }
        //pag +=list+": ";
        while(renglonBuscador<=renglonObjetivo&&i<tamA){
            pag += archivo.charAt(i);
            if (archivo.charAt(i) == '\n') {
                if (cont==imprimir) {
                    renglonBuscador++;
                    cont=1;
                }else{
                    cont++;
                }
            }
            i++;
        }
        txtArchivo.setText(pag);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

   

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtrasArchivo;
    private javax.swing.JButton btnSeparar;
    private javax.swing.JButton btnSiguienteArchivo;
    private javax.swing.JButton btnSimbolos;
    private javax.swing.JButton exit;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPaginaA;
    private javax.swing.JMenu mnArchivo;
    private javax.swing.JPanel pnlAnalisis;
    private javax.swing.JPanel pnlArchivo;
    private javax.swing.JPanel pnlControles;
    private javax.swing.JMenuItem smnCargarArchivo;
    private javax.swing.JMenuItem smnSalir;
    private javax.swing.JTextArea txtArchivo;
    // End of variables declaration//GEN-END:variables
}
